#ifndef CREATE_LOGO_H
#define CREATE_LOGO_H

#define CREATE_LOGO "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\nMMMMMMMMMMMMMMMMMM9= ....... ?\"MMMMMMMMMMMMMMMMMMM\r\nMMMMMMMMMMMMMMM@'.JMMMMMMMMMMMa,,WMMMMMMMMMMMMMMMM\r\nMMMMMMMMN.-?\"\"'.MMMMMMMMMMMMMMMMN,,MMMMMMMMMMMMMMM\r\nMMMMMMMMMMa        _?\"\"HMMMMMMMMMMp HMMMMMMMMMMMMM\r\nMMMMMMMMMMM#                ?7\"\"MMM].MMMMMMMMMMMMM\r\nMMMMMMMMMMMF.N,                ..... (7TWMMMMMMMMM\r\nMMMMMMMMMMM],MMm.     ..gMMMMMMMMMMM_-MMMMMMMMMMMM\r\nMMMMMMMMMMM].MMMM,   .MMMMMMMMMMMMMM (MMMMMMMMMMMM\r\nMMMMMMMMMMMN UMMMMN, (MMMMMMMMMMMMMF.MMMMMMMMMMMMM\r\nMMMMMMMMMMMMb UMMMMMm.MMMMMMMMMMMMF JMMMMMMMMMMMMM\r\nMMMMMMMMMMMMMN.?MMMMMMeMMMMMMMMMM3.dMMMMMMMMMMMMMM\r\nMMMMMMMMMMMMMMMa.?WMMMMNMMMMMM#=.(MMMMMMMMMMMMMMMM\r\nMMMMMMMMMMMMMMMMMNJ..?\"\"\"\"\"7`..MMMMMMMMMMMMMMMMMMM\r\nMMMMMMMMMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMM\r\n"

#endif /* CREATE_LOGO_H */